services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
    ports:
      - "5432:5432"
    networks:
      - wsl-net
    restart: always
  rag-api:
    depends_on:
      - pgvector
    build: .
    container_name: rag-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    networks:
      - wsl-net
    restart: always

networks:
  wsl-net:
    external: true
    name: wsl-net
